version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  sbank_http:
    image: rondao/sbank
    ports:
      - "20000:20000"
      - "20001:20001"
      - "20002:20002"
    depends_on:
      - kafka
    command: sbank-http run 20000
  sbank_deposit:
    image: rondao/sbank
    depends_on:
      - kafka
    command: sbank-deposit run
  sbank_withdrawn:
    image: rondao/sbank
    depends_on:
      - kafka
    command: sbank-withdrawn run
  sbank_statement:
    image: rondao/sbank
    depends_on:
      - kafka
    command: sbank-statement run
  sbank_db:
    image: rondao/sbank
    depends_on:
      - kafka
    command: sbank-db run
    
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
